### ISSUE TITLE
Warning: Non-serializable values were found in the navigation state.

### ISSUE THREAD

**Issue by aymericcucherousset** [cesi-pedoncule/RR-Lib#2]
Non-serializable values were found in the navigation state. Check:

Login > params.rest.instance (Function)

This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See [https://reactnavigation.org/docs/troubleshooting#i-get-the-w…g-non-serializable-values-were-found-in-the-navigation-state](https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state) for more details.

**Comment by Horziox** [comment]
The problem comes from the native react navigation which seems to deserialize class and turn them into JS objects
But it's impossible for an object to have
