### ISSUE TITLE
Edit Resource Error

### ISSUE THREAD

**Issue by HM22-code** [cesi-pedoncule/RR-Lib#7]
Error Axios while editing resource. 
"/categories/" is missing before the id of categories

{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","detail":"Invalid IRI \u00221edc317b-6987-6698-ab0b-cb849138bde6\u0022.","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/AbstractItemNormalizer.php","line":505,"args":[]},{"namespace":"ApiPlatform\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"denormalizeRelation","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/AbstractItemNormalizer.php","line":484,"args":[["string","categories"],["object","ApiPlatform\\Metadata\\ApiProperty"],["string","App\\Entity\\Category"],["string","1edc317b-6987-6698-ab0b-cb849138bde6"],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Category"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"api_denormalize":["boolean",true],"cache_key":["string","8975dae671360570fdacc5b69aec4245"],"deserialization_path":["string","categories"]}]]},{"namespace":"ApiPlatform\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"denormalizeCollection","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/AbstractItemNormalizer.php","line":747,"args":[["string","categories"],["object","ApiPlatform\\Metadata\\ApiProperty"],["object","Symfony\\Component\\PropertyInfo\\Type"],["string","App\\Entity\\Category"],["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Category"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"api_denormalize":["boolean",true],"cache_key":["string","8860c062e124498f02baa818151b8cba"],"deserialization_path":["string","categories"]}]]},{"namespace":"ApiPlatform\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"createAndValidateAttributeValue","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/AbstractItemNormalizer.php","line":704,"args":[["string","categories"],["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Category"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"api_denormalize":["boolean",true],"cache_key":["string","8860c062e124498f02baa818151b8cba"],"deserialization_path":["string","categories"]}]]},{"namespace":"ApiPlatform\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"createAttributeValue","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/AbstractItemNormalizer.php","line":436,"args":[["string","categories"],["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"api_denormalize":["boolean",true],"cache_key":["string","8860c062e124498f02baa818151b8cba"],"deserialization_path":["string","categories"]}]]},{"namespace":"ApiPlatform\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"setAttributeValue","file":"\/var\/www\/vendor\/symfony\/serializer\/Normalizer\/AbstractObjectNormalizer.php","line":410,"args":[["object","App\\Entity\\Resource"],["string","categories"],["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"api_denormalize":["boolean",true],"cache_key":["string","8860c062e124498f02baa818151b8cba"],"deserialization_path":["string","categories"]}]]},{"namespace":"Symfony\\Component\\Serializer\\Normalizer","short_class":"AbstractObjectNormalizer","class":"Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer","type":"-\u003E","function":"denormalize","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/AbstractItemNormalizer.php","line":212,"args":[["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"],"title":["string","Test Aut qui est et."],"description":["string","Qui quisquam explicabo qui et. Ipsum iusto natus ut dolores perferendis est modi minima. Labore repudiandae illum excepturi rerum distinctio eum fugit. Iste explicabo sunt eos voluptatum et quis et."],"isPublic":["boolean",true],"categories":["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]]}],["string","App\\Entity\\Resource"],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"api_denormalize":["boolean",true],"cache_key":["string","8860c062e124498f02baa818151b8cba"]}]]},{"namespace":"ApiPlatform\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"denormalize","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Serializer\/ItemNormalizer.php","line":70,"args":[["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"],"title":["string","Test Aut qui est et."],"description":["string","Qui quisquam explicabo qui et. Ipsum iusto natus ut dolores perferendis est modi minima. Labore repudiandae illum excepturi rerum distinctio eum fugit. Iste explicabo sunt eos voluptatum et quis et."],"isPublic":["boolean",true],"categories":["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]]}],["string","App\\Entity\\Resource"],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"object_to_populate":["object","App\\Entity\\Resource"],"api_denormalize":["boolean",true]}]]},{"namespace":"ApiPlatform\\Serializer","short_class":"ItemNormalizer","class":"ApiPlatform\\Serializer\\ItemNormalizer","type":"-\u003E","function":"denormalize","file":"\/var\/www\/vendor\/symfony\/serializer\/Serializer.php","line":238,"args":[["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"],"title":["string","Test Aut qui est et."],"description":["string","Qui quisquam explicabo qui et. Ipsum iusto natus ut dolores perferendis est modi minima. Labore repudiandae illum excepturi rerum distinctio eum fugit. Iste explicabo sunt eos voluptatum et quis et."],"isPublic":["boolean",true],"categories":["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]]}],["string","App\\Entity\\Resource"],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"object_to_populate":["object","App\\Entity\\Resource"]}]]},{"namespace":"Symfony\\Component\\Serializer","short_class":"Serializer","class":"Symfony\\Component\\Serializer\\Serializer","type":"-\u003E","function":"denormalize","file":"\/var\/www\/vendor\/symfony\/serializer\/Serializer.php","line":151,"args":[["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"],"title":["string","Test Aut qui est et."],"description":["string","Qui quisquam explicabo qui et. Ipsum iusto natus ut dolores perferendis est modi minima. Labore repudiandae illum excepturi rerum distinctio eum fugit. Iste explicabo sunt eos voluptatum et quis et."],"isPublic":["boolean",true],"categories":["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]]}],["string","App\\Entity\\Resource"],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"object_to_populate":["object","App\\Entity\\Resource"]}]]},{"namespace":"Symfony\\Component\\Serializer","short_class":"Serializer","class":"Symfony\\Component\\Serializer\\Serializer","type":"-\u003E","function":"deserialize","file":"\/var\/www\/vendor\/api-platform\/core\/src\/Symfony\/EventListener\/DeserializeListener.php","line":101,"args":[["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"],"title":["string","Test Aut qui est et."],"description":["string","Qui quisquam explicabo qui et. Ipsum iusto natus ut dolores perferendis est modi minima. Labore repudiandae illum excepturi rerum distinctio eum fugit. Iste explicabo sunt eos voluptatum et quis et."],"isPublic":["boolean",true],"categories":["array",[["string","1edc317b-6987-6698-ab0b-cb849138bde6"]]]}],["string","App\\Entity\\Resource"],["string","json"],["array",{"groups":["array",[["string","resource:put"]]],"operation_name":["string","put_resource"],"operation":["object","ApiPlatform\\Metadata\\Put"],"resource_class":["string","App\\Entity\\Resource"],"skip_null_values":["boolean",true],"iri_only":["boolean",false],"request_uri":["string","\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"uri":["string","http:\/\/api.ressourcesrelationnelles.social\/resources\/1edc317b-69ad-6a64-bbbe-cb849138bde6"],"input":["null",null],"output":["null",null],"uri_variables":["array",{"id":["string","1edc317b-69ad-6a64-bbbe-cb849138bde6"]}],"api_allow_update":["boolean",true],"object_to_populate":["object","App\\Entity\\Resource"]}]]},{"namespace":"ApiPlatform\\Symfony\\EventListener","short_class":"DeserializeListener","class":"ApiPlatform\\Symfony\\EventListener\\DeserializeListener","type":"-\u003E","function":"onKernelRequest","file":"\/var\/www\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php","line":115,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\RequestEvent"],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"WrappedListener","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"-\u003E","function":"__invoke","file":"\/var\/www\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":230,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\RequestEvent"],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"callListeners","file":"\/var\/www\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":59,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\RequestEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"dispatch","file":"\/var\/www\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php","line":153,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\RequestEvent"],["string","kernel.request"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"-\u003E","function":"dispatch","file":"\/var\/www\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":139,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\RequestEvent"],["string","kernel.request"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handleRaw","file":"\/var\/www\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":75,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handle","file":"\/var\/www\/vendor\/symfony\/http-kernel\/Kernel.php","line":202,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","function":"handle","file":"\/var\/www\/vendor\/symfony\/runtime\/Runner\/Symfony\/HttpKernelRunner.php","line":35,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Symfony\\Component\\Runtime\\Runner\\Symfony","short_class":"HttpKernelRunner","class":"Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner","type":"-\u003E","function":"run","file":"\/var\/www\/vendor\/autoload_runtime.php","line":29,"args":[]},{"namespace":"","short_class":"","class":"","type":"","function":"require_once","file":"\/var\/www\/public\/index.php","line":5,"args":[["string","\/var\/www\/vendor\/autoload_runtime.php"]]}]}

**Comment by Horziox** [comment]
Fix in **0.5.0-alpha**
